# -*- coding: utf-8 -*-
"""appstore_reviews_analyzer_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sleJNtlRxiAeEJa3nTokR6z7qWMvmPqF
"""

!pip -q install requests pandas XlsxWriter openpyxl

APP_URL = "https://apps.apple.com/ru/app/telegram/id747648890?l=en-GB&mt=12%20Telegram"
OUTPUT_XLSX = "appstore_last_100_reviews.xlsx"
LAST_N_REVIEWS = 100

import re
import time
import requests
import pandas as pd
import xml.etree.ElementTree as ET
from IPython.display import display

COUNTRY_CODES = [
    "us","gb","ru","de","fr","it","es","nl","pl","tr","ua","kz","jp","kr","cn",
    "ca","au","br","mx","se","no","dk","fi","pt","gr","cz","hu","ro","sk","at",
    "ch","be","ie","nz","sg","hk","in","id","my","th","vn","ph","za","ae","sa",
    "il","cl","ar","co","pe"
]

HEADERS = {
    "User-Agent": "Mozilla/5.0"
}

NS = {
    "atom": "http://www.w3.org/2005/Atom",
    "im": "http://itunes.apple.com/rss"
}


def extract_app_id(url: str) -> str:
    match = re.search(r"/id(\d+)", url)
    if not match:
        raise ValueError("Не удалось извлечь app_id из ссылки.")
    return match.group(1)


def safe_text(value):
    if value is None:
        return ""
    return str(value).strip()


def fetch_one_page(app_id: str, country: str, page: int):
    urls = [
        f"https://itunes.apple.com/{country}/rss/customerreviews/page={page}/id={app_id}/sortby=mostrecent/xml",
        f"https://itunes.apple.com/{country}/rss/customerreviews/id={app_id}/page={page}/sortby=mostrecent/xml",
    ]

    xml_text = None
    for url in urls:
        try:
            r = requests.get(url, headers=HEADERS, timeout=20)
            if r.status_code == 200 and r.text.strip():
                xml_text = r.text
                break
        except Exception:
            pass

    if not xml_text:
        return []

    try:
        root = ET.fromstring(xml_text)
    except Exception:
        return []

    entries = root.findall("atom:entry", NS)
    if not entries:
        return []

    rows = []

    for idx, entry in enumerate(entries):
        rating = safe_text(entry.findtext("im:rating", default="", namespaces=NS))

        # Пропускаем entry с метаданными приложения
        if not rating:
            continue

        review_id = safe_text(entry.findtext("atom:id", default="", namespaces=NS))
        author = safe_text(entry.findtext("atom:author/atom:name", default="", namespaces=NS))
        title = safe_text(entry.findtext("atom:title", default="", namespaces=NS))
        content = safe_text(entry.findtext("atom:content", default="", namespaces=NS))
        version = safe_text(entry.findtext("im:version", default="", namespaces=NS))
        updated = safe_text(entry.findtext("atom:updated", default="", namespaces=NS))

        review_text = content
        if title and content and title.lower() != content.lower():
            review_text = f"{title}. {content}"
        elif title and not content:
            review_text = title

        if not review_id:
            review_id = f"{country}_{page}_{idx}_{author}_{updated}"

        rows.append({
            "review_id": review_id,
            "author": author,
            "review": review_text,
            "rating": pd.to_numeric(rating, errors="coerce"),
            "version": version,
            "date_time": updated,
            "country": country
        })

    return rows


def fetch_reviews_for_country(app_id: str, country: str, max_pages: int = 150, sleep_sec: float = 0.15):
    country_rows = []
    seen_ids = set()
    empty_streak = 0

    for page in range(1, max_pages + 1):
        rows = fetch_one_page(app_id, country, page)

        if not rows:
            empty_streak += 1
            if empty_streak >= 2:
                break
            continue

        empty_streak = 0

        new_count = 0
        for row in rows:
            if row["review_id"] in seen_ids:
                continue
            seen_ids.add(row["review_id"])
            country_rows.append(row)
            new_count += 1

        if new_count == 0:
            break

        time.sleep(sleep_sec)

    return country_rows


def collect_last_reviews(app_url: str, last_n: int = 100):
    app_id = extract_app_id(app_url)
    all_rows = []

    print(f"app_id: {app_id}")

    for i, country in enumerate(COUNTRY_CODES, start=1):
        try:
            rows = fetch_reviews_for_country(app_id, country, max_pages=150)
            print(f"[{i}/{len(COUNTRY_CODES)}] {country}: {len(rows)} отзывов")
            all_rows.extend(rows)
        except Exception as e:
            print(f"[{i}/{len(COUNTRY_CODES)}] {country}: ошибка -> {e}")

    if not all_rows:
        raise ValueError("Не удалось собрать отзывы.")

    df = pd.DataFrame(all_rows)

    df = df.drop_duplicates(subset=["review_id"], keep="first").copy()
    df["date_time"] = pd.to_datetime(df["date_time"], errors="coerce", utc=True).dt.tz_localize(None)

    df = df.sort_values("date_time", ascending=False).reset_index(drop=True)
    df = df.head(last_n).copy()

    df = df[["author", "review", "rating", "version", "date_time", "country"]]

    return df


def save_one_sheet_excel(df: pd.DataFrame, output_path: str):
    with pd.ExcelWriter(output_path, engine="xlsxwriter", datetime_format="yyyy-mm-dd hh:mm:ss") as writer:
        df.to_excel(writer, sheet_name="reviews", index=False)

        workbook = writer.book
        worksheet = writer.sheets["reviews"]

        worksheet.set_column("A:A", 25)  # author
        worksheet.set_column("B:B", 100) # review
        worksheet.set_column("C:C", 10)  # rating
        worksheet.set_column("D:D", 15)  # version
        worksheet.set_column("E:E", 22)  # date_time
        worksheet.set_column("F:F", 10)  # country

        wrap_format = workbook.add_format({"text_wrap": True, "valign": "top"})
        worksheet.set_column("B:B", 100, wrap_format)
        worksheet.set_default_row(60)

    print(f"Excel сохранён: {output_path}")

df_reviews = collect_last_reviews(APP_URL, last_n=LAST_N_REVIEWS)

print(f"\nИтоговое количество отзывов: {len(df_reviews)}")
display(df_reviews.head(20))

save_one_sheet_excel(df_reviews, OUTPUT_XLSX)

from google.colab import files
files.download(OUTPUT_XLSX)

